[package]
name = "rust_graph_debugger"
version = "0.1.0"

authors = ["MajorX234 <majorx234@googlemail.com>"]
edition = "2021"
resolver = "2"

[[bin]]
name = "package_dependency_graph"
path = "src/package_dependency_graph/bin/main.rs"

[dependencies]
petgraph = {version = "0.6.2"}
